import type {
  GetServerSideProps,
  GetStaticPaths,
  GetStaticProps,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ItemProduct } from "../components";
import { ResponseType } from "../types";
import { ProductModel } from "../models";
import { PRODUCT_DEFAULT } from "../constants";

interface IProps {
  product: ProductModel;
}

type ParamsType = { id: string };

const ProductDetail: NextPage<IProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Demo Next.js</h1>

        <h2 className={styles.description}>Detail product</h2>

        <ItemProduct data={props.product} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

// export const getStaticPaths: GetStaticPaths<ParamsType> = async () => {
//   const res = await fetch("http://localhost:3000/api/products");
//   const products: ResponseType<ProductModel[]> = await res.json();

//   let paths: { params: ParamsType }[] = [];

//   if (products.data) {
//     paths = products.data.map((product) => ({
//       params: { id: product.id },
//     }));
//   }

//   return { paths, fallback: false };
// };

// export const getStaticProps: GetStaticProps<IProps, ParamsType> = async ({
export const getServerSideProps: GetServerSideProps<
  IProps,
  ParamsType
> = async ({ params }) => {
  const res = await fetch(`http://localhost:3000/api/products/${params?.id}`);
  const product: ResponseType<ProductModel> = await res.json();

  if (product.data) {
    return {
      props: {
        product: product.data,
      },
    };
  } else {
    return {
      props: {
        product: PRODUCT_DEFAULT,
      },
    };
  }
};

export default ProductDetail;
