import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ItemProduct } from "../components";
import { ProductModel } from "../models";
import styles from "../styles/Home.module.css";
import { ResponseType } from "../types";

interface IProps {
  products: ProductModel[];
}

const Home: NextPage<IProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Demo Next.js</h1>

        <h2 className={styles.description}>List products</h2>

        <div className={styles.grid}>
          {props.products.map((product, index) => {
            return <ItemProduct key={index} data={product} />;
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<IProps> = async () => {
  // export const getStaticProps: GetStaticProps<IProps> = async () => {
  const res = await fetch("http://localhost:3000/api/products");
  const products: ResponseType<ProductModel[]> = await res.json();

  if (products.data) {
    return {
      props: {
        products: products.data,
      },
    };
  } else {
    return {
      props: {
        products: [],
      },
    };
  }
};

export default Home;
